export default {
  allCards: [
    { name: "01", image: "01.jpg" },
    { name: "02", image: "02.jpg" },
    { name: "03", image: "03.jpg" },
    { name: "04", image: "04.jpg" },
    { name: "05", image: "05.jpg" },
    { name: "06", image: "06.jpg" },
    { name: "08", image: "07.jpg" },
    { name: "09", image: "08.jpg" },
    { name: "10", image: "09.jpg" },
    { name: "11", image: "10.jpg" },
    { name: "12", image: "11.jpg" },
    { name: "25", image: "12.jpg" },
    { name: "14", image: "14.jpg" },
    // { name: "15", image: "15.jpg" },
    // { name: "16", image: "16.jpg" },
    // { name: "17", image: "17.jpg" },
    // { name: "18", image: "18.jpg" },
    // { name: "19", image: "19.jpg" },
    // { name: "20", image: "20.jpg" },
    // { name: "21", image: "21.jpg" },
    // { name: "22", image: "22.jpg" },
    // { name: "23", image: "23.jpg" },
    // { name: "24", image: "24.jpg" },
    // { name: "25", image: "25.jpg" },
    // { name: "26", image: "26.jpg" },
    // { name: "27", image: "27.jpg" },
    // { name: "28", image: "28.jpg" },
    // { name: "29", image: "29.jpg" },
    // { name: "30", image: "30.jpg" },
    // { name: "31", image: "31.jpg" },
    // { name: "32", image: "32.jpg" },
    // { name: "33", image: "33.jpg" },
    // { name: "34", image: "34.jpg" },
    // { name: "35", image: "35.jpg" },
    // { name: "36", image: "36.jpg" },
    // { name: "37", image: "37.jpg" },
    // { name: "38", image: "38.jpg" },
    // { name: "39", image: "39.jpg" }
  ],
  
  };
  