export default {
  cardsList: [
    { name: "01", image: "../assets/animals/01.jpg" },
    { name: "02", image: "../assets/animals/02.jpg" },
    { name: "03", image: "../assets/animals/03.jpg" },
    { name: "04", image: "../assets/animals/04.jpg" },
    { name: "05", image: "../assets/animals/05.jpg" },
    { name: "06", image: "../assets/animals/06.jpg" },
    { name: "08", image: "../assets/animals/07.jpg" },
    { name: "09", image: "../assets/animals/08.jpg" },
    { name: "10", image: "../assets/animals/09.jpg" },
    { name: "11", image: "../assets/animals/10.jpg" },
    { name: "12", image: "../assets/animals/11.jpg" },
    { name: "25", image: "../assets/animals/12.jpg" },
    { name: "14", image: "../assets/animals/14.jpg" },
    { name: "15", image: "../assets/animals/15.jpg" },
    { name: "16", image: "../assets/animals/16.jpg" },
    { name: "17", image: "../assets/animals/17.jpg" },
    { name: "18", image: "../assets/animals/18.jpg" },
    { name: "19", image: "../assets/animals/19.jpg" },
    { name: "20", image: "../assets/animals/20.jpg" },
    { name: "21", image: "../assets/animals/21.jpg" },
    { name: "22", image: "../assets/animals/22.jpg" },
    { name: "23", image: "../assets/animals/23.jpg" },
    { name: "24", image: "../assets/animals/24.jpg" },
    { name: "25", image: "../assets/animals/25.jpg" },
    { name: "26", image: "../assets/animals/26.jpg" },
    { name: "27", image: "../assets/animals/27.jpg" },
    { name: "28", image: "../assets/animals/28.jpg" },
    { name: "29", image: "../assets/animals/29.jpg" },
    { name: "30", image: "../assets/animals/30.jpg" },
    { name: "31", image: "../assets/animals/31.jpg" },
    { name: "32", image: "../assets/animals/32.jpg" },
    { name: "33", image: "../assets/animals/33.jpg" },
    { name: "34", image: "../assets/animals/34.jpg" },
    { name: "35", image: "../assets/animals/35.jpg" },
    { name: "36", image: "../assets/animals/36.jpg" },
    { name: "37", image: "../assets/animals/37.jpg" },
    { name: "38", image: "../assets/animals/38.jpg" },
    { name: "39", image: "../assets/animals/39.jpg" }
  ],
  };
  